# -*- mode: ruby -*-
# vi: set ft=ruby :

# ────── Configuration ─────────
BOX_IMAGE     = "debian/trixie64"
VM_CPUS       = 2
VM_MEMORY     = 2048
SERVER_IP     = "192.168.56.110"
MGMT_NETWORK  = "192.168.151.0/24"
# ──────────────────────────────

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  config.vm.define "p2"
  config.vm.hostname = "lle-coutS"
  config.vm.network "private_network", ip: SERVER_IP

  config.vm.provider :libvirt do |lv|
    lv.memory = VM_MEMORY
    lv.cpus = VM_CPUS
    lv.management_network_name    = "p2-mgmt"
    lv.management_network_address = MGMT_NETWORK
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "file", source: "confs", destination: "/home/vagrant/manifests"
  config.vm.provision "shell", path: "scripts/init.sh"
end
