# -*- mode: ruby -*-
# vi: set ft=ruby :

# ────── CONFIGURATION ─────────
VM_CPUS       = 2
VM_MEMORY     = 2048
BOX_IMAGE     = "generic/rocky9"
BOX_VERSION   = "4.3.12"
SERVER_IP     = "192.168.56.110"
WORKER_IP     = "192.168.56.111"
SYNC_DIR_HOST = "./data"
# ──────────────────────────────

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE
  config.vm.box_version = BOX_VERSION

  # ────────────────── VM Server ──────────────────
  config.vm.define "server" do |server|
    server.vm.hostname = "lle-coutS"
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.synced_folder SYNC_DIR_HOST, "/vagrant", type: "nfs", nfs_udp: false

    server.vm.provider :libvirt do |libvirt|
      libvirt.memory = VM_MEMORY
      libvirt.cpus = VM_CPUS
    end

    server.vm.provision "shell", path: "scripts/server_init.sh"
  end

  # ────────────────── VM Worker ──────────────────
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "lle-coutSW"
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.synced_folder SYNC_DIR_HOST, "/vagrant", type: "nfs", nfs_udp: false

    worker.vm.provider :libvirt do |libvirt|
      libvirt.memory = VM_MEMORY
      libvirt.cpus = VM_CPUS
    end

    worker.vm.provision "shell", path: "scripts/worker_init.sh"
  end
end
