# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "rockylinux/8"
  config.vm.box_version = "10.0.0"
  config.ssh.shell = "zsh -l"

  # ────────────────── VM Server ──────────────────
  config.vm.define "server" do |server|
    server.vm.hostname = "lle-coutS"
    server.vm.network "private_network", ip: "192.168.56.110"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder.
    # worker.vm.synced_folder "../data", "/vagrant_data"

    server.vm.provider :virtualbox do |v|
      v.name = "Server"
      v.memory = 1024
      v.cpus = 1
    end

  server.vm.provision "shell", path: "scripts/vm_server_init.sh"
  end

  # ────────────────── VM Worker ──────────────────
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "lle-coutSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder.
    # worker.vm.synced_folder "../data", "/vagrant_data"

    worker.vm.provider :virtualbox do |v|
      v.name = "Worker"
      v.memory = 1024
      v.cpus = 1
    end

  worker.vm.provision "shell", path: "scripts/vm_server_worker_init.sh"
  end

end
