# -*- mode: ruby -*-
# vi: set ft=ruby :

# ────── Configuration ─────────
BOX_IMAGE     = "debian/trixie64"
VM_CPUS       = 1
VM_MEMORY     = 1024
SERVER_IP     = "192.168.56.110"
WORKER_IP     = "192.168.56.111"
MGMT_NETWORK  = "192.168.150.0/24"
# ──────────────────────────────

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.provider :libvirt do |lv|
    lv.management_network_name    = "p1-mgmt"
    lv.management_network_address = MGMT_NETWORK
    lv.memory = VM_MEMORY
    lv.cpus = VM_CPUS
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # ────────────────── VM Server ──────────────────
  config.vm.define "server" do |server|
    server.vm.hostname = "lle-coutS"
    server.vm.network "private_network", ip: SERVER_IP
  end
  # ────────────────── VM Worker ──────────────────
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "lle-coutSW"
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provision "ansible" do |ansible|
      ansible.playbook = "scripts/playbook.yaml"
      ansible.limit = "all"
    end
  end
end
